session_name: media-preflight-api
start_directory: ./
windows:

- window_name: media-preflight-api
  layout: tiled
  shell_command_before:
    - 'source ~/srv/media-preflight-api/bin/activate'
  panes:
    - shell_command:
        - ./manage.py runserver 0.0.0.0:7779
    - shell_command:
        - celery -A app worker -c 2 -l debug
    - cd app
    - cd app
