# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 14:22
from __future__ import unicode_literals

import base.storage
from django.db import migrations, models
import preflight.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Initialized'), (1, 'Pending'), (2, 'Processing'), (3, 'Done'), (99, 'Error')], db_index=True, default=1, verbose_name='Status')),
                ('task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('remote_uri', models.URLField(db_index=True, null=True, unique=True)),
                ('media_file', models.FileField(blank=True, null=True, storage=base.storage.OverwriteFileSystemStorage(), upload_to=preflight.models.get_media_upload_path)),
            ],
        ),
    ]
